---
# tasks file for squid
- name: Install squid
  package: 
    name: squid
    state: present

- name: Enable squid service
  service:
    name: squid
    enabled: yes

- iptables:
  table: nat
  chain: PREROUTING
  in_interface: eth1
  protocol: tcp
  match: tcp
  destination_port: 80
  jump: DNAT
  to_destination: 192.168.1.1:3128
  comment: Redirect web traffic to port 3128
become: yes

- iptables:
  table: nat
  chain: PREROUTING
  in_interface: eth0
  protocol: tcp
  match: tcp
  destination_port: 80
  jump: REDIRECT
  to_ports: 3128
  comment: Redirect web traffic to port 3128
become: yes

- name: Install squid.conf
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
    owner: root
    group: root
    mode: 0644
    validate: squid -k parse -f %s
  notify:
    - restart squid
 
